name: PerchExtras
main: com.olziedev.spotextras.SpotExtras
version: ${version}
author: Olzie
api-version: 1.13
permissions:
  antibackteleport.command:
    description: Antiback teleport command
    default: op
  potion.command.milk:
    description: Use the milk command
    default: op
  realestate.admin:
    description: Open the admin manage menu
    default: op
depend:
  - WorldGuard
  - DiscordSRV
  - Essentials
  - Vault
  - GriefPrevention
